# .github/release.yml
# 配置自动生成的 Release Notes 格式
changelog:
  exclude:
    labels:
      - ignore-for-release
      - dependencies
      - github_actions
  categories:
    - title: 🚀 新功能 / New Features
      labels:
        - feature
        - enhancement
        - new
    - title: 🐛 修复 / Bug Fixes  
      labels:
        - fix
        - bug
        - bugfix
        - hotfix
    - title: 📚 文档 / Documentation
      labels:
        - docs
        - documentation
    - title: 🔧 其他改进 / Other Changes
      labels:
        - "*" 