version: 1
formatters:
  simple:
    format: '%(asctime)s - %(levelname)s %(name)s %(filename)s:%(lineno)d - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: output/log/log.log
    when: midnight
    interval: 1
    backupCount: 30
    encoding: utf-8
    delay: false

root:
  level: DEBUG
  handlers: [console, file]