version: 1
formatters:
  simple:
    format: '%(asctime)s - %(levelname)s %(name)s %(filename)s:%(lineno)d - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: output/log/log.log

loggers:
  mylogger:
    level: DEBUG
    handlers: [ console ,file]
    propagate: no
root:
  level: DEBUG
  handlers: [ console ,file]